from flask import Flask, request, jsonify
import requests
import sqlite3

app = Flask(__name__)

# ======================
# CONFIG
# ======================
BOT_TOKEN = "8730476133:AAEq9Y5kmz-uOEBc8dDeIF_gdfaMpBb6GjA"
OXAPAY_API_KEY = "NMIAS7-T6YZZA-ITKKN9-1M1YWL"

# ======================
# DATABASE
# ======================
def init_db():
    conn = sqlite3.connect("data.db")
        c = conn.cursor()

            c.execute("""
                    CREATE TABLE IF NOT EXISTS deposits (
                                track_id TEXT PRIMARY KEY,
                                            user_id INTEGER,
                                                        amount REAL,
                                                                    status TEXT
                                                                            )
                                                                                """)

                                                                                    c.execute("""
                                                                                            CREATE TABLE IF NOT EXISTS users (
                                                                                                        user_id INTEGER PRIMARY KEY,
                                                                                                                    balance REAL DEFAULT 0
                                                                                                                            )
                                                                                                                                """)

                                                                                                                                    conn.commit()
                                                                                                                                        conn.close()

                                                                                                                                        init_db()

                                                                                                                                        # ======================
                                                                                                                                        # TELEGRAM MESSAGE
                                                                                                                                        # ======================
                                                                                                                                        def send_message(chat_id, text):
                                                                                                                                            url = f"https://api.telegram.org/bot{BOT_TOKEN}/sendMessage"
                                                                                                                                                requests.post(url, data={
                                                                                                                                                        "chat_id": chat_id,
                                                                                                                                                                "text": text,
                                                                                                                                                                        "parse_mode": "HTML"
                                                                                                                                                                            })

                                                                                                                                                                            # ======================
                                                                                                                                                                            # CREATE INVOICE (OXAPAY)
                                                                                                                                                                            # ======================
                                                                                                                                                                            @app.route("/create_invoice", methods=["POST"])
                                                                                                                                                                            def create_invoice():
                                                                                                                                                                                data = request.json

                                                                                                                                                                                    amount = data.get("amount")
                                                                                                                                                                                        user_id = data.get("user_id")

                                                                                                                                                                                            res = requests.post(
                                                                                                                                                                                                    "https://api.oxapay.com/v1/payment/invoice",
                                                                                                                                                                                                            json={
                                                                                                                                                                                                                        "amount": amount,
                                                                                                                                                                                                                                    "currency": "USDT",
                                                                                                                                                                                                                                                "order_id": f"{user_id}_{amount}"
                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                            ).json()

                                                                                                                                                                                                                                                                return jsonify({
                                                                                                                                                                                                                                                                        "payLink": res.get("payLink"),
                                                                                                                                                                                                                                                                                "trackId": res.get("trackId")
                                                                                                                                                                                                                                                                                    })

                                                                                                                                                                                                                                                                                    # ======================
                                                                                                                                                                                                                                                                                    # SAVE DEPOSIT
                                                                                                                                                                                                                                                                                    # ======================
                                                                                                                                                                                                                                                                                    @app.route("/save_deposit", methods=["POST"])
                                                                                                                                                                                                                                                                                    def save_deposit():
                                                                                                                                                                                                                                                                                        data = request.json

                                                                                                                                                                                                                                                                                            track_id = data["track_id"]
                                                                                                                                                                                                                                                                                                user_id = data["user_id"]
                                                                                                                                                                                                                                                                                                    amount = data["amount"]

                                                                                                                                                                                                                                                                                                        conn = sqlite3.connect("data.db")
                                                                                                                                                                                                                                                                                                            c = conn.cursor()

                                                                                                                                                                                                                                                                                                                c.execute("""
                                                                                                                                                                                                                                                                                                                        INSERT INTO deposits VALUES (?, ?, ?, 'pending')
                                                                                                                                                                                                                                                                                                                            """, (track_id, user_id, amount))

                                                                                                                                                                                                                                                                                                                                conn.commit()
                                                                                                                                                                                                                                                                                                                                    conn.close()

                                                                                                                                                                                                                                                                                                                                        return {"status": "saved"}

                                                                                                                                                                                                                                                                                                                                        # ======================
                                                                                                                                                                                                                                                                                                                                        # WEBHOOK (OXAPAY CALLBACK)
                                                                                                                                                                                                                                                                                                                                        # ======================
                                                                                                                                                                                                                                                                                                                                        @app.route("/webhook", methods=["POST"])
                                                                                                                                                                                                                                                                                                                                        def webhook():
                                                                                                                                                                                                                                                                                                                                            data = request.json

                                                                                                                                                                                                                                                                                                                                                track_id = data.get("trackId")
                                                                                                                                                                                                                                                                                                                                                    status = data.get("status")

                                                                                                                                                                                                                                                                                                                                                        conn = sqlite3.connect("data.db")
                                                                                                                                                                                                                                                                                                                                                            c = conn.cursor()

                                                                                                                                                                                                                                                                                                                                                                c.execute("SELECT user_id, amount, status FROM deposits WHERE track_id=?", (track_id,))
                                                                                                                                                                                                                                                                                                                                                                    row = c.fetchone()

                                                                                                                                                                                                                                                                                                                                                                        if not row:
                                                                                                                                                                                                                                                                                                                                                                                return "not found"

                                                                                                                                                                                                                                                                                                                                                                                    user_id, amount, old_status = row

                                                                                                                                                                                                                                                                                                                                                                                        if status == "paid" and old_status != "paid":

                                                                                                                                                                                                                                                                                                                                                                                                c.execute("UPDATE deposits SET status='paid' WHERE track_id=?", (track_id,))

                                                                                                                                                                                                                                                                                                                                                                                                        # update balance
                                                                                                                                                                                                                                                                                                                                                                                                                c.execute("SELECT balance FROM users WHERE user_id=?", (user_id,))
                                                                                                                                                                                                                                                                                                                                                                                                                        bal = c.fetchone()

                                                                                                                                                                                                                                                                                                                                                                                                                                if bal:
                                                                                                                                                                                                                                                                                                                                                                                                                                            new_bal = bal[0] + amount
                                                                                                                                                                                                                                                                                                                                                                                                                                                        c.execute("UPDATE users SET balance=? WHERE user_id=?", (new_bal, user_id))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                else:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            new_bal = amount
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        c.execute("INSERT INTO users VALUES (?, ?)", (user_id, new_bal))

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                conn.commit()

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        send_message(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    user_id,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                f"""
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ✅ <b>Deposit Successful</b>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                💰 Amount: {amount} USDT
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                💼 New Balance: {new_bal} USDT
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                """
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        )

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            conn.close()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return "ok"

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                # ======================
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                # TEST ROUTE
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                # ======================
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                @app.route("/")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                def home():
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return "OxaPay Server Running"

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    # ======================
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    # RUN
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    # ======================
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if __name__ == "__main__":
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        app.run()